require_relative 'vendor/scopes-n-groups/lib/scope'

require_relative 'geometry/init'

require_relative 'lib/player'
require_relative 'lib/game_objects'
require_relative 'lib/game_object'
require_relative 'lib/gun'
require_relative 'lib/shell'
require_relative 'lib/track'
require_relative 'lib/battery'
require_relative 'lib/connectable'
require_relative 'lib/tracked_bot'
require_relative 'lib/pew_pew'
require_relative 'lib/engineer'
require_relative 'lib/facility'
require_relative 'lib/recharger'
require_relative 'lib/metal_derrick'
require_relative 'lib/factory'
require_relative 'lib/pew_pew_factory'
require_relative 'lib/engineer_factory'
require_relative 'lib/connection'
require_relative 'lib/world'
